### PR TITLE
Add support for SwiftPM

### PR DESCRIPTION
**Pull request by kiliankoe**
The `#if` guards were necessary to get this to build, at least for now. It does build successfully and I can run the tests. A lot of them are failing however, but I'm not sure if that's to be expected or not.

Limiting this to specific platform versions also appeared to be necessary due to the usage of `NSAttributedString.DocumentReadingOptionKey` in ParserUtils.swift. 

Huge thanks for putting this project together by the way! ❤️

### CODE REVIEW

**Comment by kiliankoe** [comment]
Hi @alexander-albers, I just saw that you're not watching this repo, so you might not have seen this. Sorry to pull you in like this 🙈

**Comment by alexander-albers** [comment]
Hi, thanks a lot for your contribution! I'm still fairly new to dependency management in the Apple world (I do have some experience with dependency managers for other languages), so I have a few questions to you.
First, is it possible to integrate the linked dependencies of Swift PM into Xcode? In that case we could get rid of CocoaPods all together and just use SPM, right? Or are there any advantages of using both CocoaPods and SPM? Also, how could we integrate universal framework support into TripKit? Currently, there is only a target for iOS and watchOS, but as far as I understand there is a method for supporting all platforms at once.
Next, have you had any chance to figure out why `NSAttributedString.DocumentReadingOptionKey` requires iOS 11? According to the Apple documentation the keys require iOS 11, but the method in `String` has been added in iOS 7...
Lastly, the tests probably fail because you haven't specified the necessary secrets. Providers that extend `AbstractEfaProvider` should work without any additional changes.

**Comment by kiliankoe** [comment]
> First, is it possible to integrate the linked dependencies of Swift PM into Xcode? In that case we could get rid of CocoaPods all together and just use SPM, right?

As of a few minutes ago, exactly that! 

> Next, have you had any chance to figure out why NSAttributedString.DocumentReadingOptionKey requires iOS 11? According to the Apple documentation the keys require iOS 11, but the method in String has been added in iOS 7...
> Lastly, the tests probably fail because you haven't specified the necessary secrets. Providers that extend AbstractEfaProvider should work without any additional changes.

I'll look into both of those things 👍

**Comment by alexander-albers** [comment]
Hi, sorry for the delay - I did not manage to find enough time (and motivation :P) to restructure both this project and my app. 

I've now added support for SPM as well as macOS and tvOS targets by myself. That way it was easier for me to also update all project files, etc. The changes are available in the latest commit, so I'm closing this pull request.

**Comment by kiliankoe** [comment]
Argh, I totally forgot about this, sorry! Huge thanks for adding SwiftPM support though! ❤️

**Pull request closed without merging**
